name: Django CI

on:
  push:
    branches: [ feature/add_ci_pipeline ]
  pull_request:
    branches: [ feature/add_ci_pipeline ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v2



